name: news_flutter_riverpod
description: Flutter NewsApp usign flutter_riverpod

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  cached_network_image: ^3.2.3
  cupertino_icons: ^1.0.2
  dio: ^5.1.1
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  flutter_riverpod: ^2.3.4
  freezed_annotation: ^2.2.0
  google_fonts: ^4.0.3

dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2

flutter:
  uses-material-design: true

  assets:
    - .env
