package dev.donmanuel.dailyquotes.data

import androidx.room.Entity
import androidx.room.PrimaryKey


/**
 * Data class representing a Quote entity in the database.
 *
 * @property id The unique identifier for the quote. Auto-generated by the database.
 * @property text The text of the quote.
 * @property author The author of the quote.
 */

@Entity(tableName = "quotes")
data class Quote(
    @PrimaryKey(autoGenerate = true) val id: Int = 0,
    var text: String,
    var author: String
)