schema: lib/graphql/schema.graphql
extensions:
  endpoints:
    Default GraphQL Endpoint:
      url: https://api.sampleapis.com/avatar/graphql
      headers:
        user-agent: JS GraphQL
      introspect: true
